config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat.id)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price_per_night %>
  <%= f.text_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<h1>All our Flats</h1>
<div class="row mb-10">
  <% @flats.each do |flat|%>
    <div class="col-md-4">
      <div class= "card">
        <h3>
          <%= flat.name %>
        </h3>
        <p><%= flat.address %></p>
        <div>
          <span><i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night  %></span>
          <span><%= flat.number_of_guests %></span>
        </div>
        <div> <%= link_to "More Info", flat_path(flat.id)%></div>
        <div> <%= link_to "Edit", edit_flat_path(flat.id)%></div>

         <div> <%= link_to "Remove",
            flat_path(flat.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %></div>
      </div>
    </div>
  <% end %>
  </div>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price_per_night %>
  <%= f.text_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>


<%= link_to "Back", flats_path%>

app/views/flats/show.html.erb
<h2> <%= @flat.name %></h2>
<p><%= @flat.address %></p>

<div>
  <h3>A bit more about this flat</h3>
  <p><%= @flat.description %></p>
</div>

<div>
  <h3>Details</h3>
  <p><%= @flat.number_of_guests %><span> </span> <i class="fa-solid fa-euro-sign"></i><%= @flat.price_per_night %></p>

</div>



<%= link_to 'Back', flats_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <div>
        <h3>Simple Airbnb</h3>
      </div>
      <div>
        <button><%= link_to "Add Flat", new_flat_path %></button>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>